"""
Serve the latest signals JSON data.

Reads from _site/data/signals.json (generated by GitHub Actions)
and serves it as a JSON API response with CORS support.
"""

import json
from http.server import BaseHTTPRequestHandler
from pathlib import Path


DATA_FILE = Path(__file__).parent.parent / "_site" / "data" / "signals.json"


class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        if DATA_FILE.exists():
            data = DATA_FILE.read_text()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Cache-Control", "public, max-age=60")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(data.encode())
        else:
            self.send_response(404)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({
                "error": "No signals data available yet",
                "hint": "Signals are generated by GitHub Actions on market hours"
            }).encode())
