"""
Serve the latest signals JSON data.

Reads from _site/data/signals.json (generated by GitHub Actions)
and serves it as a JSON API response with CORS support, ETag
for conditional requests, and OPTIONS for CORS preflight.
"""

import json
import hashlib
from http.server import BaseHTTPRequestHandler
from pathlib import Path


DATA_FILE = Path(__file__).parent.parent / "_site" / "data" / "signals.json"

CORS_HEADERS = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, If-None-Match",
    "Access-Control-Max-Age": "86400",
}


class handler(BaseHTTPRequestHandler):
    def _send_cors_headers(self):
        for key, value in CORS_HEADERS.items():
            self.send_header(key, value)

    def do_OPTIONS(self):
        self.send_response(204)
        self._send_cors_headers()
        self.end_headers()

    def do_GET(self):
        if DATA_FILE.exists():
            data = DATA_FILE.read_text()

            # Generate ETag from content hash
            etag = '"' + hashlib.md5(data.encode()).hexdigest()[:16] + '"'

            # Check If-None-Match for conditional request
            if_none_match = self.headers.get("If-None-Match")
            if if_none_match and if_none_match == etag:
                self.send_response(304)
                self._send_cors_headers()
                self.send_header("ETag", etag)
                self.end_headers()
                return

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Cache-Control", "public, max-age=60")
            self.send_header("ETag", etag)
            self._send_cors_headers()
            self.end_headers()
            self.wfile.write(data.encode())
        else:
            self.send_response(404)
            self.send_header("Content-Type", "application/json")
            self._send_cors_headers()
            self.end_headers()
            self.wfile.write(json.dumps({
                "error": "No signals data available yet",
                "hint": "Signals are generated by GitHub Actions on market hours"
            }).encode())
